redis-server:
  listen: 0.0.0.0:6379
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  redis: true
  redis_db: 0
  timeout: 5
  server_retry_timeout: 2000
  server_failure_limit: 2
  servers:
   - redis1:6379:1
   - redis2:6379:1
   - redis3:6379:1
